export const categories = ['IoT', 'Web Development', 'Mobile Applications', 'Photography', 'Gamification'];

export const allProducts = [
  // IoT Category
  {
    id: 'iot-1',
    title: 'Sistem Presensi RFID',
    price: 'Rp. 1.000.000',
    image: 'https://picsum.photos/seed/iot1/400/300',
    description: 'Complete smart home setup with voice control and energy monitoring. Tailored to your specific home layout.',
    category: 'IoT',
  },
  {
    id: 'iot-2',
    title: 'Hidroponik',
    price: 'Rp. 1.000.000',
    image: 'https://picsum.photos/seed/iot2/400/300',
    description: 'High-precision sensors for manufacturing and predictive maintenance. Includes real-time dashboard.',
    category: 'IoT',
  },
  {
    id: 'iot-3',
    title: 'Sensor Suhu',
    price: 'Rp. 1.000.000',
    image: 'https://picsum.photos/seed/iot3/400/300',
    description: 'Soil moisture and weather monitoring for optimized farming and increased crop yield.',
    category: 'IoT',
  },

  // Web Development Category
  {
    id: 'web-1',
    title: 'Setting SEO',
    price: 'Rp. 1.000.000',
    image: 'https://picsum.photos/seed/web1/400/300',
    description: 'Custom online store with payment gateway integration, inventory management, and user profiles.',
    category: 'Web Development',
  },
  {
    id: 'web-2',
    title: 'Desain UI/UX',
    price: 'Rp. 1.000.000',
    image: 'https://picsum.photos/seed/web2/400/300',
    description: 'Professional company website with SEO optimization, blog, and CMS for easy content updates.',
    category: 'Web Development',
  },
  {
    id: 'web-3',
    title: 'Website Portofolio',
    price: '$2500.00',
    image: 'https://picsum.photos/seed/web3/400/300',
    description: 'Minimum Viable Product development for startups and new business ideas. Fast time-to-market.',
    category: 'Web Development',
  },
  {
    id: 'web-4',
    title: 'Website Bisnis/UMKM',
    price: '$300.00',
    image: 'https://picsum.photos/seed/web4/400/300',
    description: 'High-converting landing page design and development for your marketing campaigns.',
    category: 'Web Development',
  },
  {
    id: 'web-5',
    title: 'Website Blog/Artikel',
    price: '$300.00',
    image: 'https://picsum.photos/seed/web4/400/300',
    description: 'High-converting landing page design and development for your marketing campaigns.',
    category: 'Web Development',
  },
  {
    id: 'web-6',
    title: 'Jasa Pembuatan Web Pendidikan/Lembaga',
    price: '$300.00',
    image: 'https://picsum.photos/seed/web4/400/300',
    description: 'High-converting landing page design and development for your marketing campaigns.',
    category: 'Web Development',
  },
  {
    id: 'web-7',
    title: 'Website Landing Page',
    price: 'Rp. 1.000.000',
    image: 'https://picsum.photos/seed/web1/400/300',
    description: 'Custom online store with payment gateway integration, inventory management, and user profiles.',
    category: 'Web Development',
  },
  {
    id: 'web-8',
    title: 'Website Company Profile',
    price: 'Rp. 1.000.000',
    image: 'https://picsum.photos/seed/web2/400/300',
    description: 'Professional company website with SEO optimization, blog, and CMS for easy content updates.',
    category: 'Web Development',
  },

  // Mobile Applications Category
  {
    id: 'mobile-1',
    title: 'iOS Native App',
    price: '$3000.00',
    image: 'https://picsum.photos/seed/mobile1/400/300',
    description: 'High-performance native iOS application built with Swift, optimized for the latest Apple devices.',
    category: 'Mobile Applications',
  },
  {
    id: 'mobile-2',
    title: 'Android Native App',
    price: '$2800.00',
    image: 'https://picsum.photos/seed/mobile2/400/300',
    description: 'Robust native Android application built with Kotlin, supporting a wide range of devices.',
    category: 'Mobile Applications',
  },
  {
    id: 'mobile-3',
    title: 'Cross-Platform App',
    price: '$4000.00',
    image: 'https://picsum.photos/seed/mobile3/400/300',
    description: 'React Native or Flutter app that works seamlessly on both iOS and Android from a single codebase.',
    category: 'Mobile Applications',
  },
  {
    id: 'mobile-4',
    title: 'Desain UI/UX',
    price: '$1500.00',
    image: 'https://picsum.photos/seed/mobile4/400/300',
    description: 'Complete overhaul of your existing mobile app interface for better user engagement.',
    category: 'Mobile Applications',
  },

  // Photography Category
  {
    id: 'photo-1',
    title: 'Wedding Photography',
    price: '$1500.00',
    image: 'https://picsum.photos/seed/photo1/400/300',
    description: 'Full-day wedding coverage with edited high-resolution photos and a premium physical album.',
    category: 'Photography',
  },
  {
    id: 'photo-2',
    title: 'Product Photography',
    price: '$500.00',
    image: 'https://picsum.photos/seed/photo2/400/300',
    description: 'Professional studio shots for your e-commerce products, including lifestyle and white-background images.',
    category: 'Photography',
  },
  {
    id: 'photo-3',
    title: 'Corporate Event Coverage',
    price: '$800.00',
    image: 'https://picsum.photos/seed/photo3/400/300',
    description: 'Comprehensive photo coverage for conferences, seminars, and corporate parties.',
    category: 'Photography',
  },
  {
    id: 'photo-4',
    title: 'Portrait Session',
    price: '$250.00',
    image: 'https://picsum.photos/seed/photo4/400/300',
    description: 'Professional headshots and creative portraits for personal branding or team pages.',
    category: 'Photography',
  },

  // Gamification Category
  {
    id: 'game-1',
    title: 'Employee Engagement App',
    price: '$2000.00',
    image: 'https://picsum.photos/seed/game1/400/300',
    description: 'Gamified platform with leaderboards and badges to boost employee productivity and morale.',
    category: 'Gamification',
  },
  {
    id: 'game-2',
    title: 'Customer Loyalty Program',
    price: '$1800.00',
    image: 'https://picsum.photos/seed/game2/400/300',
    description: 'Interactive rewards system to increase customer retention and lifetime value.',
    category: 'Gamification',
  },
  {
    id: 'game-3',
    title: 'Educational Game',
    price: '$3500.00',
    image: 'https://picsum.photos/seed/game3/400/300',
    description: 'Fun and interactive learning game tailored for students or corporate compliance training.',
    category: 'Gamification',
  },
  {
    id: 'game-4',
    title: 'Marketing Mini-Game',
    price: '$1200.00',
    image: 'https://picsum.photos/seed/game4/400/300',
    description: 'Short, addictive web game designed to capture leads and promote your brand on social media.',
    category: 'Gamification',
  },
];
